Booki/Controllers/ControloAcessosController.cs
using Booki.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Booki.Helper;

namespace Booki.Controllers
{
    public class ControloAcessosController : BaseController
    {
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(model);
            }
            
            string sql = $@"SELECT u.id_user, u.nome_completo
                                FROM utilizador u 
                            WHERE 1=1
                                AND u.username = @username
                                AND u.password = @password";

            bool loggedIn = false;

            using (var connection = new SqlConnection(ConnectionString))
            using (var command = new SqlCommand(sql, connection))
            {
                connection.Open();

                command.Parameters.AddWithValue("@username", model.Username);
                command.Parameters.AddWithValue("@password", model.Password);
                
                using (var reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        loggedIn = !string.IsNullOrEmpty(reader["id_user"].ToString());
                        model.Nome = reader["nome_completo"].ToString();
                        model.IdUser = Convert.ToInt16(reader["id_user"]);
                    }
                        
                }

                connection.Close();
            }

            if (loggedIn)
            {
                LogInUser(model);
                ViewBag.LoggedIn = loggedIn;
                ViewBag.UserLogin = model;
            }
            else
            {
                return Json(new
                {
                    Notify = true,
                    Message = "Credenciais erradas",
                    Type = "alert-warning",
                    Time ="7500"
                });
            }
                

            return Json(new
            {
                Redirect = true,
                UrlRedirect = Url.Action("Index", "Home")
            });
        }

        public ActionResult Registo()
        {
            var model = new RegistoModel
            {
                ListaLocalizacoes = CustomHelper.GetListaLocalizacoes(ConnectionString)
            };
            
            return View(model);
        }
        [HttpPost]
        public ActionResult Registo(RegistoModel model)
        {
            if (!ModelState.IsValid)
            {
                model.ListaLocalizacoes = CustomHelper.GetListaLocalizacoes(ConnectionString);
                return PartialView(model);
            }
                
            string sql = $@"INSERT INTO utilizador (
                                    [username],
                                    [password],
                                    [nome_completo],
                                    [email],
                                    [morada],
                                    [codigo_postal],
                                    [id_localizacao]
                                   ) VALUES (
                                    @username,
                                    @password,
                                    @nome_completo,
                                    @email,
                                    @morada,
                                    @codigo_postal,
                                    @id_localizacao)";

            using (var connection = new SqlConnection(ConnectionString))
            using (var command = new SqlCommand(sql, connection))
            {
                connection.Open();

                command.Parameters.AddWithValue("@username", model.Username);
                command.Parameters.AddWithValue("@password", model.Password);
                command.Parameters.AddWithValue("@nome_completo", model.Nome);
                command.Parameters.AddWithValue("@email", model.Email);
                command.Parameters.AddWithValue("@morada", model.Morada);
                command.Parameters.AddWithValue("@codigo_postal", model.CodigoPostal);
                command.Parameters.AddWithValue("@id_localizacao", model.IdLocalizacao);
                
                command.ExecuteNonQuery();

                connection.Close();
            }
            
            return Json(new { });
        }
        public ActionResult Logout()
        {
            ViewBag.LoggedIn = false;
            LogOutUser();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult EditarPerfil()
        {
            ViewBag.LoggedIn = IsLoggedIn();

            var utilizador = (LoginModel)Session[SessionUtilizador];

            var model = new RegistoModel
            {
                ListaLocalizacoes = CustomHelper.GetListaLocalizacoes(ConnectionString),
                IdUser = utilizador.IdUser
            };
            
            var sql = "SELECT * from utilizador where id_user = @userId";

            using (var connection = new SqlConnection(ConnectionString))
            using (var command = new SqlCommand(sql, connection))
            {
                connection.Open();

                command.Parameters.AddWithValue("@userId", utilizador.IdUser);

                using (var reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        model.Username = reader["UserName"].ToString();
                        model.Password = reader["password"].ToString();
                        model.Nome = reader["nome_completo"].ToString();
                        model.Email = reader["Email"].ToString();
                        model.Morada = reader["morada"].ToString();
                        model.CodigoPostal = reader["codigo_postal"].ToString();
                        model.IdLocalizacao = Convert.ToInt16(reader["id_localizacao"]);
                    }
                }

                connection.Close();
            }

            return View(model);
        }
        [HttpPost]
        public ActionResult EditarPerfil(RegistoModel model)
        {
            ModelState.Remove("Password");

            if (!ModelState.IsValid)
            {
                model.ListaLocalizacoes = CustomHelper.GetListaLocalizacoes(ConnectionString);
                return PartialView(model);
            }

            var sql = $@"update utilizador set 
                                    [username] = @userName,
                                    [nome_completo] = @nome_completo,
                                    [email] = @email,
                                    [morada] = @morada,
                                    [codigo_postal] = @codigo_postal,
                                    [id_localizacao] = @id_localizacao

                                    where id_user = @id_user";

            using (var connection = new SqlConnection(ConnectionString))
            using (var command = new SqlCommand(sql, connection))
            {
                connection.Open();

                command.Parameters.AddWithValue("@id_user", model.IdUser);
                command.Parameters.AddWithValue("@username", model.Username);
                command.Parameters.AddWithValue("@nome_completo", model.Nome);
                command.Parameters.AddWithValue("@email", model.Email);
                command.Parameters.AddWithValue("@morada", model.Morada);
                command.Parameters.AddWithValue("@codigo_postal", model.CodigoPostal);
                command.Parameters.AddWithValue("@id_localizacao", model.IdLocalizacao);

                command.ExecuteNonQuery();

                connection.Close();
            }

            return Json(new {
                Notify = true,
                Type = CustomHelper.Constantes.TiposNotificacao.Success,
                Message = "Alterações gravadas com sucesso!",
                Time = 7500
            });
        }
    }
}

Booki/Views/ControloAcessos/EditarPerfil.cshtml
@model Booki.Models.RegistoModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Ajax.BeginForm("EditarPerfil", "ControloAcessos", new AjaxOptions
{
    OnSuccess = "OnSucessForm"
}))
{
    @Html.HiddenFor(x => x.IdUser)

    <style>
        .content-controlo-acesso {
            padding: 25px 37px;
            margin: 40px 0%;
        }
        .breadcrumb{
            background: red;
        }
            .breadcrumb .breadcrumb-item {
                color: white;
            }
    </style>

    <div class="content-controlo-acesso">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Perfil do utilizador @Model.Nome</li>
            </ol>
        </nav>

        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Nome de utilizador</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.TextBoxFor(o => o.Username, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(o => o.Username)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Nome completo</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.TextBoxFor(o => o.Nome, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(o => o.Nome)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Email</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.TextBoxFor(o => o.Email, new { @class = "form-control input-sm", @type = "email" })
                @Html.ValidationMessageFor(o => o.Email)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Morada</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.TextBoxFor(o => o.Morada, new { @class = "form-control input-sm" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Código postal</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.TextBoxFor(o => o.CodigoPostal, new { @class = "form-control input-sm" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Localização</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @{
                    var listaLocal = Model.ListaLocalizacoes.Select(x => new SelectListItem
                    {
                        Text = x.Localizacao,
                        Value = x.IdLocalizacao.ToString()
                    }).ToList();
                }

                @Html.DropDownListFor(model => model.IdLocalizacao, listaLocal, "-- Selecionar Localizacao --", new { @class = "form-control" })
                @Html.ValidationMessageFor(o => o.Username)
            </div>
        </div>
        <div class="row" style="margin-top: 15px;">
            <div class="col-md-3 col-sm-3 col-xs-3">
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                <button class="btn btn-primary float-right" type="submit">Guardar alterações</button>
            </div>
        </div>
    </div>
}

Booki/Views/ControloAcessos/Login.cshtml
@model Booki.Models.LoginModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Ajax.BeginForm("Login", "ControloAcessos", new AjaxOptions
{
    OnSuccess = "OnSucessForm",
    HttpMethod = "POST"
}))
{
    <div class="content-controlo-acesso">
        <h2 class="title-controlo">Booki - Login</h2>

        <div class="form-group">
            <label>Nome de utilizador</label>
            @Html.TextBoxFor(o => o.Username, new { @class = "form-control input-sm", @placeholder = "Nome de utilizador" })

        </div>
        <div class="form-group">
            <label>Palavra-passe</label>
            @Html.PasswordFor(o => o.Password, new { @class = "form-control input-sm", @placeholder = "Palavra-passe" })
            @Html.ValidationMessageFor(o => o.Password)
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block btn-lg">Entrar</button>
        </div>

        <a href="@Url.Action("Registo", "ControloAcessos")" class="link-controlo">Criar nova conta</a>

    </div>
}

Booki/Views/ControloAcessos/Registo.cshtml
@model Booki.Models.RegistoModel

@{
    ViewBag.Title = "Registo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Ajax.BeginForm("Registo", "ControloAcessos", new AjaxOptions
{
    OnSuccess = "OnSucessForm"
}))
{
    <style>
        .content-controlo-acesso {
            padding: 25px 37px;
            margin: 40px 8%;
        }
    </style>

    <div class="content-controlo-acesso">
        <h2 class="title-controlo">Booki - Criar nova conta</h2>

        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Nome de utilizador</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.TextBoxFor(o => o.Username, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(o => o.Username)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Palavra-passe</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.PasswordFor(o => o.Password, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(o => o.Username)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Nome completo</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.TextBoxFor(o => o.Nome, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(o => o.Nome)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Email</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.TextBoxFor(o => o.Email, new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(o => o.Email)
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Morada</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.TextBoxFor(o => o.Morada, new { @class = "form-control input-sm" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Código postal</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @Html.TextBoxFor(o => o.CodigoPostal, new { @class = "form-control input-sm" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <label class="control-label">Localização</label>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                @{
                    var listaLocal = Model.ListaLocalizacoes.Select(x => new SelectListItem
                    {
                        Text = x.Localizacao,
                        Value = x.IdLocalizacao.ToString()
                    }).ToList();
                }

                @Html.DropDownListFor(model => model.IdLocalizacao, listaLocal, "-- Selecionar Localizacao --", new { @class = "form-control" })
                @Html.ValidationMessageFor(o => o.Username)
            </div>
        </div>
        <div class="row" style="margin-top: 15px;">
            <div class="col-md-3 col-sm-3 col-xs-3">
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8">
                <a href="@Url.Action("Login", "ControloAcessos")">Já possui uma conta? Faça login.</a>
                <button class="btn btn-primary float-right" type="submit">Registar</button>
            </div>
        </div>
    </div>
}